### ISSUE TITLE
not able to use rotateWhenChanged

### ISSUE THREAD

**Issue by jankaacc** [upbound/provider-azuread#81]
### What problem are you facing?

I would like to automatically rotate the credentials for app in Azure for that I am creating appilcation 
and Password MR for it like:

```yaml
apiVersion: applications.azuread.upbound.io/v1beta1
kind: Password
metadata:
  name: password-sp
spec:
  deletionPolicy: Orphan
  forProvider:
    applicationObjectIdSelector:
      matchControllerRef: true
    rotateWhenChanged:
      rotateEveryMonth: "2024-01"
```

rotateWhenChanged should update the credentials whenever value of one of key values pairs will change.
When I am updating value to:

```yaml
    rotateWhenChanged:
      rotateEveryMonth: "2024-02"
```

terraform running under the hood is destroying the resource and recreates this results in error like 
```
 message: 'observe failed: cannot run plan: plan failed: Instance cannot be destroyed:
        Resource azuread_application_password.scc-dev-profile-sp-r2lxl-nvgcs has lifecycle.prevent_destroy
        set, but the plan calls for this resource to be destroyed. To avoid this error
        and continue with the plan, either disable lifecycle.prevent_destroy or reduce
        the scope of the plan using the -target flag.'
      reason: ReconcileError
      status: "False"
      type: Synced
```

### How could Official Azuread Provider help solve your problem?

Is it possible to make lifecycle configurable so we could do like:

```yaml
apiVersion: applications.azuread.upbound.io/v1beta1
kind: Password
metadata:
  name: password-sp
spec:
  deletionPolicy: Orphan
  forProvider:
    applicationObjectIdSelector:
      matchControllerRef: true
    rotateWhenChanged:
      rotateEveryMonth: "2024-01"
    lifecycle:
      preventDestroy: false
```

**Comment by twobiers** [comment]
I'm using the[function-go-templating](https://github.com/crossplane-contrib/function-go-templating/) and have solved this by removing the Password from the desired state when nearing the expiration date, then adding it back. This effectively implements rotation. As you see its very hard to maintain, so maybe its worth writing a custom function for this or introduce native support for destroy operations in crossplane provider as you proposed.

```yaml
{{- $passwordResourceName := "app-password-example" }}
{{- $passwordFromObservedState := getComposedResource . $passwordResourceName }}
{{- $endDate := dig "resources" $passwordResourceName "resource" "spec" "initProvider" "endDate" (now | date_modify "4380h" | date "2006-01-02T15:04:05Z") .observed }}
{{- $shouldRotatePassword := gt (now | date_modify "+1h" | unixEpoch) ($endDate | mustToDate "2006-01-02T15:04:05Z" | unixEpoch) }}
{{- if not $shouldRotatePassword }}
apiVersion: applications.azuread.upbound.io/v1beta1
kind: Password
metadata:
  annotations:
    {{ setResourceNameAnnotation $passwordResourceName }}
  name: "example"
spec:
  managementPolicies: ["Observe", "Create", "Update", "Delete"]
  forProvider:
    applicationObjectIdSelector:
      matchControllerRef: true
  initProvider:
    {{- $endDate := dig "resources" $passwordResourceName "resource" "spec" "initProvider" "endDate" (now | date_modify "+4380h" | date "2006-01-02T15:04:05Z") .observed }}
    endDate: {{ $endDate }}
{{- end }}
```
